Wedding.Web/Models/ErrorViewModel.cs
using System;

namespace Wedding.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Wedding.Web/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wedding.Web.Models
{
    public class HomeViewModel
    {
    }
}

Wedding.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Abstractions.Services;
using Wedding.Web.Models;
using System.Threading.Tasks;

namespace Wedding.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IWeddingStudioGroupService _studioGroupService;

        public HomeController(IWeddingStudioGroupService studioGroupService)
        {
            _studioGroupService = studioGroupService;
        }
        public async Task<IActionResult> Index()
        {

            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Header()
        {
            return PartialView("_Header");
        }
    }
}

Wedding.Web/Controllers/StudioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abstractions.Services;
using Microsoft.AspNetCore.Mvc;

namespace Wedding.Web.Controllers
{
    public class StudioController : Controller
    {
        private readonly IWeddingStudioService _weddingStudioService;

        public StudioController(IWeddingStudioService weddingStudioService)
        {
            _weddingStudioService = weddingStudioService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult ProductsList(int studioId)
        {
            var listProducts = _weddingStudioService.GetWeddingStudioAsync(studioId);
            return View(listProducts);
        }
    }
}

Wedding.Web/ViewComponents/Home/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Wedding.Web.ViewComponents.Home
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Footer"));
        }
    }
}

Wedding.Web/ViewComponents/Home/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

using Abstractions.Services;

namespace Wedding.Web.ViewComponents.Home
{
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Header"));
        }
    }
}

Wedding.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Wedding.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Wedding.Web/Views/Shared/Components/Footer/Footer.cshtml
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12">
                <!-- footer-widget -->
                <div class="footer-widget">
                    <a href="#"><img src="images/footer-logo.png" alt="" class="mb20"></a>
                    <p class="mb10">Vestibulum ante elit, convallis quis nibh in, vulputate rhoncus massa. In hac habitasse platea dictumst.</p>
                    <p>In hac habitasse platea dictumst simple dummy content here.</p>
                </div>
            </div>
            <!-- /.footer-widget -->
            <!-- footer-widget -->
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-12">
                <div class="footer-widget">
                    <h3 class="widget-title">
                        Contact Address
                    </h3>
                    <p>
                        4998 Elk Creek Road Canton,
                        <br> GA 30114
                    </p>
                    <p class="mb0 text-default">+0-800-1234-123</p>
                    <p class="mb0 text-default">info@realwed.com</p>
                </div>
            </div>
            <!-- /.footer-widget -->
            <!-- footer-widget -->
            <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6 col-12">
                <div class="footer-widget">
                    <h3 class="widget-title">
                        About Company
                    </h3>
                    <ul class="listnone">
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Pricing Plan</a></li>
                        <li><a href="#">Meet The Team</a></li>
                    </ul>
                </div>
            </div>
            <!-- /.footer-widget -->
        </div>
    </div>
</div>
<!-- tiny-footer-section -->
<div class="tiny-footer">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-right">
                <p>© 2019 The41Wedding. All Rights Reserved.</p>
            </div>
        </div>
    </div>
</div>

Wedding.Web/Views/Shared/Components/Header/Header.cshtml
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-12 col-sm-12 col-12">
                <!-- header-logo -->
                <div class="header-logo">
                    <a href="index.html"><img src="~/theme/images/logo_1.png" style="width: auto; height: 48px; object-fit: contain;" alt="Wedding Vendor & Supplier Directory HTML Template "></a>
                </div>
                <!-- /.header-logo -->
            </div>
            <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">
                <!-- navigations -->
                <div id="navigation">
                    <ul>
                        <li>
                            <a href="/" title="#">Home</a>
                        </li>
                        <li>
                            <a href="#" title="#">Vendors</a>
                        </li>
                        <li>
                            <a href="#" title="#">Suppliers</a>
                            <ul>
                                <li><a href="supplier-dresses-list.html" title="">Dresses</a></li>
                                <li><a href="supplier-cake-list.html" title="">Cakes</a></li>
                                <li><a href="supplier-florist-list.html" title="">Florist</a></li>
                                <li><a href="supplier-photographer-list.html" title="">Photographers</a></li>
                                <li><a href="supplier-videographer-list.html" title="">Videographer</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" title="#">Real Weddings</a>
                        </li>
                        <li>
                            <a href="#" title="#">Blog</a>
                        </li>
                        <li>
                            <a href="#" title="#">About us</a>
                        </li>
                        <li>
                            <a href="#" title="">User Panel</a>
                            <ul>
                                <li>
                                    <a href="#" title="">Vendor Dashboard</a>
                                <li>
                                    <a href="#" title="">Couple Dashboard</a>
                                </li>
  
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.navigations -->
            </div>
            <div class="col-xl-2 col-lg-2 text-right col-md-2 col-sm-12 col-12 d-none d-xl-block d-lg-block">
                <!-- header-btn -->
                <div class="header-btn">
                    <a href="couple-form.html" class="btn btn-primary btn-sm">Login</a>
                </div>
                <!-- /.header-btn -->
            </div>
        </div>
    </div>
</div>

Wedding.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title> Wedding Vendor &amp; Supplier Directory HTML Template - RealWed </title>
    <!-- Bootstrap -->
    <link href="~/theme/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <!-- FontAwesome icon -->
    <link href="~/theme/fontawesome/css/fontawesome-all.css" rel="stylesheet" />
    <!-- Fontello icon -->
    <link href="~/theme/fontello/css/fontello.css" rel="stylesheet" />
    <!-- OwlCarosuel CSS -->
    <link href="~/theme/css/owl.carousel.css" rel="stylesheet" />
    <link href="~/theme/css/owl.theme.default.css" rel="stylesheet" />
    <!-- Favicon icon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/theme/images/favicon.ico">
    <!-- Style CSS -->
    <link href="~/theme/css/style.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!-- header-top -->
    <partial name="_Topbar.cshtml" />
    <!--/.header-top -->
    <!-- header -->
    @(await Component.InvokeAsync("Header"))
<!-- /.header -->

    @RenderBody()
    <!-- footer-section -->
    @(await Component.InvokeAsync("Footer"))
    <!-- /.tiny-footer-section -->
    <a href="javascript:" id="return-to-top"><i class="fa fa-angle-up"></i></a>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/theme/js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/theme/js/bootstrap.min.js"></script>
    <script src="~/theme/js/menumaker.min.js"></script>
    <!-- owl-carousel js -->
    <script src="~/theme/js/owl.carousel.min.js"></script>
    <!-- nice-select js -->
    <script src="~/theme/js/jquery.nice-select.min.js"></script>
    <script src="~/theme/js/fastclick.js"></script>
    <script src="~/theme/js/custom-script.js"></script>
    <script src="~/theme/js/return-to-top.js"></script>
</body>

</html>

Wedding.Web/Views/Shared/_Topbar.cshtml
<div class="header-top">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-xl-6 col-lg-6 col-sm-6 col-md-6 col-sm-6 col-6 d-none d-xl-block d-lg-block d-md-block">
                <div class="header-text">
                    <p class="wlecome-text">Welcome to Wedding Directory HTML Template.</p>
                </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-sm-6 col-md-6 col-sm-12 col-12">
                <div class="header-text text-right">
                    <p>Bạn muốn cung cấp dịch vụ? <a href="vendor-form.html" class="text-white">Liên hệ ngay.</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

Wedding.Web/Views/Studio/ProductsList.cshtml
@model
@{
    ViewData["Title"] = "ProductsList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="vendor-thumbnail">
                        <!-- Vendor thumbnail -->
                        <div class="vendor-img">
                            <!-- Vendor img -->
                            <a href="#"><img src="images/supplier-1.jpg" alt="" class="img-fluid"></a>
                            <div class="wishlist-sign"><a href="#" class="btn-wishlist"><i class="fa fa-heart"></i></a></div>
                        </div>
                        <!-- /.Vendor img -->
                        <div class="vendor-content">
                            <!-- Vendor Content -->
                            <h2 class="vendor-title"><a href="#" class="title">Aavis Dresses</a></h2>
                            <p class="vendor-address">Baroda, Gujarat.</p>
                        </div>
                        <!-- /.Vendor Content -->
                        <div class="vendor-meta">
                            <div class="vendor-meta-item vendor-meta-item-bordered">
                                <span class="vendor-price">
                                    $150
                                </span>
                                <span class="vendor-text">Start From</span>
                            </div>
                            <div class="vendor-meta-item vendor-meta-item-bordered">
                                <span class="rating-star">
                                    <i class="fa fa-star rated"></i>
                                    <i class="fa fa-star rated"></i>
                                    <i class="fa fa-star rated"></i>
                                    <i class="fa fa-star rated"></i>
                                    <i class="fa fa-star rate-mute"></i>
                                </span>
                                <span class="rating-count vendor-text">(20)</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="pagination justify-content-center">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item active"><a class="page-link " href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>